#=================================================
# https://github.com/P3TERX/Actions-OpenWrt
# Description: Build OpenWrt using GitHub Actions
# Lisence: MIT
# Author: P3TERX
# Blog: https://p3terx.com
#=================================================

name: Build OpenWrt ssr for mi 4A G version
on:
  watch:
    types: started

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Initialization environment
      run: |
        wget https://archive.openwrt.org/snapshots/trunk/ramips/mt7621/OpenWrt-SDK-ramips-mt7621_gcc-5.3.0_musl-1.1.16.Linux-x86_64.tar.bz2
        tar jxf OpenWrt-SDK-ramips-mt7621_gcc-5.3.0_musl-1.1.16.Linux-x86_64.tar.bz2
        cd OpenWrt-SDK-*
        # 添加 feeds
        git clone https://github.com/shadowsocks/openwrt-feeds.git package/feeds
        # 获取 shadowsocks-libev Makefile
        git clone https://github.com/shadowsocks/openwrt-shadowsocks.git package/shadowsocks-libev
        # 选择要编译的包 Network -> shadowsocks-libev
        contains(github.event.action, 'ssh')
        make package/shadowsocks-libev/compile V=99
        
