#=================================================
# https://github.com/P3TERX/Actions-OpenWrt
# Description: Build OpenWrt using GitHub Actions
# Lisence: MIT
# Author: P3TERX
# Blog: https://p3terx.com
#=================================================

name: Build OpenWrt ssr for mi 4A G version
on:
  watch:
    types: started

env:
  SSH_ACTIONS: true

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Initialization environment
      run: |
         git clone  https://github.com/shadowsocksrr/shadowsocksr-libev openwrt-ssr-3.3.4
         tar zcf openwrt-ssr-3.3.4.tgz  openwrt-ssr-3.3.4
   
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: openwrt-ssr-3.3.4.tgz
        asset_name: mything
        tag: ${{ github.ref }}
        overwrite: true   
   #
   # - name: Upload the artifacts
   #   uses: skx/github-action-publish-binaries@master
   #   env:
   #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
   #   with:
   #       args: 'openwrt-ssr-3.3.4.tgz' 
     
#    - name: Upload to release
#      uses: JasonEtco/upload-to-release@master
#      with:
#          args: "openwrt-ssr-3.3.4.tgz application/zip"
#      env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}        


        
