#=================================================
# https://github.com/P3TERX/Actions-OpenWrt
# Description: Build OpenWrt using GitHub Actions
# Lisence: MIT
# Author: P3TERX
# Blog: https://p3terx.com
#=================================================

name: Build OpenWrt ssr for mi 4A G version
on:
  watch:
    types: started

env:
  SSH_ACTIONS: true

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Initialization environment
      run: |
        wget https://archive.openwrt.org/snapshots/trunk/ramips/mt7621/OpenWrt-SDK-ramips-mt7621_gcc-5.3.0_musl-1.1.16.Linux-x86_64.tar.bz2
        echo "::set-output name=status::1"
        tar jxf OpenWrt-SDK-ramips-mt7621_gcc-5.3.0_musl-1.1.16.Linux-x86_64.tar.bz2
        echo "::set-output name=status::2"
        ls
        cd OpenWrt-SDK-ramips-mt7621_gcc-5.3.0_musl-1.1.16.Linux-x86_64
        git clone https://github.com/shadowsocks/openwrt-feeds.git package/feeds
        echo "set-output name=status::4"
        git clone https://github.com/shadowsocks/openwrt-shadowsocks.git package/shadowsocks-libev
        echo "set-output name=status::5"
  
  - name: make menuconfig 
      uses: xuesong/debugger-action@master
      if: env.SSH_ACTIONS == 'true' || contains(github.event.action, 'ssh')

  - name: start build
        echo "set-output name=status::6"
        make package/shadowsocks-libev/compile V=99
        echo "set-output name=status::7"
        
