#=================================================
# https://github.com/P3TERX/Actions-OpenWrt
# Description: Build OpenWrt using GitHub Actions
# Lisence: MIT
# Author: P3TERX
# Blog: https://p3terx.com
#=================================================

name: Build OpenWrt ssr for mi 4A G version
on:
  watch:
    types: started

env:
  SSH_ACTIONS: true

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Initialization environment
      run: |
         git clone  https://github.com/shadowsocksrr/shadowsocksr-libev openwrt-ssr-3.3.4
         tar zcf openwrt-ssr-3.3.4.tgz  openwrt-ssr-3.3.4
   
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: openwrt-ssr-3.3.4.tgz
        asset_name: release.tgz
        tag: ${{ github.ref }}
        overwrite: true   
   


        
